# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.

name: charmed-hpc-terraform tests
on:
  workflow_call:
  pull_request:

jobs:
  ci:
    name: Charmed HPC CI
    uses: canonical/hpc-team/.github/workflows/charmed-hpc-ci.yaml@main
    with:
      run-test: false
      just-version: "1.58.0"
      setup-commands: |
        sudo snap install opentofu --classic --channel latest/stable
        sudo snap install terragrunt --classic --channel latest/stable
